### ISSUE TITLE
Alpha release checklist

### ISSUE THREAD

**Issue by trainman419** [trainman419/topic_rpc#1]
List of things to do before I make a public/alpha release of topic_rpc
- [x] python API
- [ ] Doxygen documentation
- [x] enforce single-server restriction
- [x] explicit client API for waiting for the server
- [ ] client timeout/retry/fail
- [x] build system support for generating python shims

Additional items for a 1.0 release:
- [ ] Automated tests
- [ ] Tutorials
- [ ] Test multi-threaded and with nodelets
- [ ] API for setting the queue size. Reasonable defaults.
- [ ] server version which takes a shared_ptr to a context object
- [ ] try for API parity with existing ROS service API
- [ ] backward compatibility with existing services
- [ ] asynchronous client APIs (call with callback, wait for response)
